<?php
declare(strict_types=1);

require_once __DIR__ . '/../../includes/init.php';

require_role(['admin'], '../login.php');

$page_title="Create Account";
$page_desc="Create staff and student accounts. Student ID is generated automatically.";
$base_path='../';

$faculties = $pdo->query("SELECT id, name FROM faculties ORDER BY name")->fetchAll();
$semesters = $pdo->query("SELECT id, name FROM semesters ORDER BY id")->fetchAll();

$flash='';
$error='';

if (is_post()) {
  if (!csrf_verify()) $error="Invalid request.";
  else {
    $full_name = post('full_name');
    $email = post('email');
    $role = post('role');
    $password = post('password');

    $faculty_id = post_int('faculty_id', 0);
    $semester_id = post_int('semester_id', 0);

    if ($full_name === '' || $email === '' || $password === '') {
      $error="Please fill all required fields.";
    } elseif (!in_array($role, ['staff','student'], true)) {
      $error="Admin can only create staff or student accounts.";
    } elseif ($role === 'student' && ($faculty_id <= 0 || $semester_id <= 0)) {
      $error="Please select faculty and semester for student.";
    } else {
      try {
        $pdo->beginTransaction();

        $hash = password_hash($password, PASSWORD_DEFAULT);
        $stmt = $pdo->prepare("INSERT INTO users (full_name,email,password_hash,role) VALUES (?,?,?,?)");
        $stmt->execute([$full_name,$email,$hash,$role]);
        $userId = (int)$pdo->lastInsertId();

        if ($role === 'student') {
          $stmt = $pdo->prepare("INSERT INTO students (user_id, student_uid, faculty_id, semester_id, attendance_percent)
                                 VALUES (?, 'TEMP', ?, ?, 0.00)");
          $stmt->execute([$userId, $faculty_id, $semester_id]);

          $studentId = (int)$pdo->lastInsertId();
          $studentUid = 'SRMS-' . date('Y') . '-' . str_pad((string)$studentId, 5, '0', STR_PAD_LEFT);

          $stmt = $pdo->prepare("UPDATE students SET student_uid=? WHERE id=?");
          $stmt->execute([$studentUid, $studentId]);

          $subStmt = $pdo->prepare("SELECT id FROM subjects WHERE faculty_id=? AND semester_id=?");
          $subStmt->execute([$faculty_id, $semester_id]);
          $subs = $subStmt->fetchAll();

          $ins = $pdo->prepare("INSERT IGNORE INTO grades (student_id, subject_id, marks, grade_letter)
                                VALUES (?,?,0,'F')");
          foreach ($subs as $s) $ins->execute([$studentId, (int)$s['id']]);
        }

        $pdo->commit();
        $flash="Account created successfully.";
      } catch (Throwable $t) {
        $pdo->rollBack();
        $error="Could not create account. Email may already exist.";
      }
    }
  }
}

require_once __DIR__ . '/../../includes/header.php';
?>

<section class="card">
  <h1>Create Account</h1>
  <p>Admin can create staff and student accounts. Student ID is generated by the system.</p>

  <?php if ($flash): ?><div class="notice ok" data-autohide="1"><?= e($flash) ?></div><?php endif; ?>
  <?php if ($error): ?><div class="notice bad"><?= e($error) ?></div><?php endif; ?>

  <form method="post" action="create_user.php">
    <?= csrf_input() ?>

    <div class="form-row">
      <div>
        <label for="full_name">Full name</label>
        <input id="full_name" name="full_name" required maxlength="120" placeholder="Full name">
      </div>
      <div>
        <label for="email">Email</label>
        <input id="email" name="email" type="email" required maxlength="160" placeholder="name@example.com">
      </div>
    </div>

    <div class="form-row">
      <div>
        <label for="role">Account type</label>
        <select id="role" name="role" required>
          <option value="staff">staff</option>
          <option value="student">student</option>
        </select>
      </div>
      <div>
        <label for="password">Temporary password</label>
        <input id="password" name="password" type="password" required minlength="6" placeholder="Set initial password">
      </div>
    </div>

    <div class="form-row">
      <div>
        <label for="faculty_id">Faculty (student only)</label>
        <select id="faculty_id" name="faculty_id">
          <option value="0">Select faculty</option>
          <?php foreach ($faculties as $f): ?>
            <option value="<?= (int)$f['id'] ?>"><?= e($f['name']) ?></option>
          <?php endforeach; ?>
        </select>
      </div>

      <div>
        <label for="semester_id">Semester (student only)</label>
        <select id="semester_id" name="semester_id">
          <option value="0">Select semester</option>
          <?php foreach ($semesters as $s): ?>
            <option value="<?= (int)$s['id'] ?>"><?= e($s['name']) ?></option>
          <?php endforeach; ?>
        </select>
      </div>
    </div>

    <div class="actions">
      <button class="btn primary" type="submit">Create account</button>
      <a class="btn" href="dashboard.php">Back</a>
    </div>
  </form>
</section>

<?php require_once __DIR__ . '/../../includes/footer.php'; ?>